// اختبار تبويب «تحليل النتائج» (ص-٢١): python3 -m http.server 8765 ثم node tests/analysis-test.js
const { chromium } = require('playwright'); const fs=require('fs');
const MOCK = fs.readFileSync(__dirname+'/mock-firebase.js','utf8');
const OUT='/home/claude/injaz/out/analysis/';
let FAIL=0, ERRS=0; const ok=(c,m)=>{ console.log((c?'  ✓ ':'  ✗ ')+m); if(!c) FAIL++; };
const mkNames=(p,n)=>Array.from({length:n},(_,i)=>p+' '+(i+1));
const A=mkNames('طالب أ',20).map((n,i)=>({seat:'1000'+(100+i),name:n,classCode:'م1أ'}));
const B=mkNames('طالب ب',10).map((n,i)=>({seat:'2000'+(100+i),name:n,classCode:'م1ب'}));
const classes=[{name:'أول متوسط (أ)',code:'م1أ',createdBy:'u1'},{name:'أول متوسط (ب)',code:'م1ب',createdBy:'u1'}];
// صف أ: درجة المشروعات من ١٠ ← [7,5,3,2,3] ممتاز..ضعيف
const scoresA=[9.5,9.5,9.5,9.5,9.5,9.5,9.5, 8.5,8.5,8.5,8.5,8.5, 7.5,7.5,7.5, 6,6, 3,3,3];
(async()=>{
  const b=await chromium.launch();
  const mk=async(session,db)=>{
    const ctx=await b.newContext({viewport:{width:1280,height:900}});
    await ctx.route(/jsdelivr|cdnjs|googleapis|gstatic|opencv/, r=>{ if(/firebase-app-compat/.test(r.request().url())) return r.fulfill({status:200,contentType:'application/javascript',body:MOCK}); r.fulfill({status:200,contentType:'application/javascript',body:''}); });
    await ctx.addInitScript(([s,db])=>{ window.__mockUid='U_'+s.userId; localStorage.setItem('cls_session',JSON.stringify(s)); localStorage.setItem('__mockdb',JSON.stringify(db));
      window.__alerts=[]; window.alert=m=>window.__alerts.push(m); window.confirm=()=>true; window.print=()=>{}; window.__printed=[]; window.open=()=>({document:{write(h){window.__printed.push(h)},close(){}},focus(){},print(){}}); },[session,db]);
    const p=await ctx.newPage(); p.on('pageerror',e=>{ ERRS++; console.log('PAGEERR',e.message); });
    await p.goto('http://127.0.0.1:8765/omr.html'); await p.waitForTimeout(2200); await p.evaluate(()=>{ window.alert=m=>window.__alerts.push(m); }); // mn-dialog.js يستبدل alert عند التحميل
    await p.evaluate(([st,cl,sa])=>{ state.students=st; state.fullStudents=st; state.classes=cl; state.fullClasses=cl;
      state.workCfg.header={edu:'الإدارة العامة للتعليم بمكة المكرمة',school:'ثانوية الملك فيصل',teacher:'معلم تجريبي',principal:'مدير تجريبي',year:'١٤٤٧هـ',term:'الفصل الأول'};
      state.workLog={}; state.workLog['م1أ']={}; state.students.filter(s=>s.classCode==='م1أ').forEach((s,i)=>{ state.workLog['م1أ'][s.seat]={events:[],exams:{},bands:{},scores:{p1_proj:sa[i]}}; });
      state.workLog['م1ب']={}; state.students.filter(s=>s.classCode==='م1ب').forEach((s,i)=>{ if(i<8) state.workLog['م1ب'][s.seat]={events:[],exams:{},bands:{},scores:{p1_proj:[10,9,8,7,6,5,4,2][i]}}; });
    },[[...A,...B],classes,scoresA]);
    return p; };
  const DB={'schools/S2':{name:'ثانوية الملك فيصل'},'users/sa1':{authUid:'U_sa1',active:true,role:'schoolAdmin',username:'مدير',schools:{S2:{role:'teacher'}}},
    'users/c1':{authUid:'U_c1',active:true,username:'موجه الطلاب',schools:{S2:{role:'counselor',active:true,assignedClasses:['__all__']}}}};
  const S={userId:'sa1',username:'مدير',role:'schoolAdmin',schoolId:'S2',period:'first',ctxKey:'school:S2'};
  const p=await mk(S,DB);
  console.log('1. التبويب');
  await p.evaluate(()=>showTab('cloud'));
  ok(await p.isVisible('#cloudLogWrap') && !(await p.isVisible('#resAnCard')),'يبدأ بسجل الأعمال');
  await p.click('#cloudSubAn'); await p.waitForTimeout(300);
  ok(await p.isVisible('#resAnCard') && !(await p.isVisible('#cloudLogWrap')),'يفتح تحليل النتائج');
  ok((await p.locator('#anClasses input.anc').count())===2,'خياران للفصول');
  ok(/اختر فصلاً/.test(await p.textContent('#anReportHost')),'رسالة اختيار الفصل');
  console.log('2. بند المشروعات لفصل أ (٢٠ طالبًا)');
  await p.selectOption('#anMetric','i:p1_proj'); await p.waitForTimeout(100);
  ok((await p.inputValue('#anScale'))==='10','درجة القياس تؤخذ من وزن البند: '+await p.inputValue('#anScale'));
  await p.check('#anClasses input.anc[value="م1أ"]'); await p.waitForTimeout(200);
  let d=await p.evaluate(()=>({cnt:AN_LAST.reports[0].stats.cnt,n:AN_LAST.reports[0].stats.n,mean:AN_LAST.reports[0].stats.mean,max:AN_LAST.reports[0].stats.max,min:AN_LAST.reports[0].stats.min,sum:AN_LAST.reports[0].stats.sum,ach:AN_LAST.reports[0].stats.ach,ex:AN_LAST.reports[0].excluded}));
  ok(JSON.stringify(d.cnt)==='[7,5,3,2,3]','التوزيع '+JSON.stringify(d.cnt));
  ok(d.n===20 && d.max===9.5 && d.min===3 && Math.abs(d.mean-7.625)<1e-9 && Math.abs(d.sum-152.5)<1e-9 && Math.abs(d.ach-76.25)<1e-9,'الإحصاءات n=20 mean=7.625 ach=76.25');
  const txt=await p.textContent('#anReportHost');
  ok(/١٠ - ٩/.test(txt)==false || true,'(تخطّي)');
  ok(txt.includes('الإدارة العامة للتعليم بمكة المكرمة') && txt.includes('ثانوية الملك فيصل'),'الترويسة: الإدارة والمدرسة من بيانات المدرسة');
  ok(txt.includes('٧٦.٢٥٪') && txt.includes('١٥٢.٥'),'نسبة التحصيل ومجموع الدرجات بالأرقام الهندية');
  const ranges=await p.$$eval('#anReportHost .an-lv .an-row .an-box[dir=ltr]',e=>e.map(x=>x.textContent));
  ok(ranges.join('|')==='١٠ - ٩|٨.٩٩ - ٨|٧.٩٩ - ٧|٦.٩٩ - ٥|٤.٩٩ - ٠','النطاقات: '+ranges.join('|'));
  console.log('3. درجة القياس ٤٠ كما في المثال (٣٦/٣٢/٢٨/٢٠)');
  await p.fill('#anScale','40'); await p.dispatchEvent('#anScale','change'); await p.waitForTimeout(150);
  const r40=await p.$$eval('#anReportHost .an-lv .an-row .an-box[dir=ltr]',e=>e.map(x=>x.textContent));
  ok(r40.join('|')==='٤٠ - ٣٦|٣٥.٩٩ - ٣٢|٣١.٩٩ - ٢٨|٢٧.٩٩ - ٢٠|١٩.٩٩ - ٠','النطاقات: '+r40.join('|'));
  await p.fill('#anScale','10'); await p.dispatchEvent('#anScale','change');
  console.log('4. فصلان: تقرير مستقل لكل فصل + استبعاد من بلا درجة');
  await p.check('#anClasses input.anc[value="م1ب"]'); await p.waitForTimeout(200);
  d=await p.evaluate(()=>({k:AN_LAST.reports.length,n:AN_LAST.reports.map(r=>r.stats.n),ex:AN_LAST.reports.map(r=>r.excluded),cmp:!!document.querySelector('#anReportHost .an-cmp'),pages:document.querySelectorAll('#anReportHost .an-pg .anr').length,mean:AN_LAST.reports.map(r=>r.stats.mean)}));
  ok(d.k===2 && d.pages===2,'تقريران مستقلان على الشاشة ('+d.k+'/'+d.pages+')');
  ok(JSON.stringify(d.n)==='[20,8]' && JSON.stringify(d.ex)==='[0,2]','عدد كل فصل منفصل: '+JSON.stringify(d.n)+' واستبعاد '+JSON.stringify(d.ex));
  ok(Math.abs(d.mean[0]-7.625)<1e-9 && Math.abs(d.mean[1]-6.375)<1e-9,'متوسط كل فصل بمفرده: '+d.mean.join(' / '));
  ok(!d.cmp,'لا جدول مقارنة بين الفصول');
  ok(/استُبعد ٢ طالب/.test(await p.textContent('#anReportHost')),'سطر الاستبعاد ظاهر في تقرير الفصل ب');
  console.log('5. بنود أخرى');
  await p.selectOption('#anMetric','all'); await p.waitForTimeout(150);
  ok(/لا توجد درجات/.test(await p.textContent('#anReportHost'))==false,'مجموع الفترة: ما زال فيه بيانات ('+(await p.textContent('#anReportHost')).slice(0,40)+')');
  ok((await p.inputValue('#anScale'))==='100','مجموع الفترة من ١٠٠');
  await p.selectOption('#anMetric','g:p1_g2'); await p.waitForTimeout(150);
  ok(/لا توجد درجات مرصودة/.test(await p.textContent('#anReportHost')),'بند بلا درجات ← رسالة واضحة');
  await p.selectOption('#anMetric','i:p1_proj'); await p.waitForTimeout(150);
  console.log('6. فترة ثانية فارغة');
  await p.selectOption('#anPeriod','1'); await p.waitForTimeout(150);
  ok(/لا توجد درجات مرصودة/.test(await p.textContent('#anReportHost')),'الفترة الثانية بلا درجات ← رسالة'); await p.selectOption('#anPeriod','0'); await p.selectOption('#anMetric','i:p1_proj'); await p.waitForTimeout(150);
  await p.uncheck('#anClasses input.anc[value="م1ب"]'); await p.fill('#anSubject','الرياضيات'); await p.fill('#anExam','الاختبار النهائي'); await p.waitForTimeout(200);
  console.log('7. الطباعة');
  await p.evaluate(()=>{ window.__printed.length=0; anPrint(); });
  const html=await p.evaluate(()=>window.__printed.join(''));
  ok(html.includes('an-pg{page-break-after:always') && html.includes('class="an-pg"'),'فاصل صفحات بين التقارير');
  ok(html.includes('class="anr"') && html.includes('@page{size:A4 portrait') && html.includes('الاختبار النهائي') && html.includes('مادة [الرياضيات]'),'نافذة الطباعة: A4 عمودي والمربع والعنوان');
  ok(html.includes('<svg') && html.includes('وزارة التعليم'),'الشعار حاضر');
  // لقطات
  const pr=await b.newContext({viewport:{width:794,height:1123}}); const pp=await pr.newPage();
  await pp.setContent(html.replace(/<script>[\s\S]*?<\/script>/g,''),{waitUntil:'load'}); await pp.emulateMedia({media:'print'}); await pp.addStyleTag({content:'html{padding:8mm}'});
  const h=await pp.evaluate(()=>Math.ceil(document.querySelector('.anr').getBoundingClientRect().height)+30);
  await pp.screenshot({path:OUT+'report-print.png',fullPage:true}); console.log('   ارتفاع الصفحة المطبوعة (بكسل):',h,' المتاح ≈ ',1123);
  ok(h<=1050,'التقرير الأحادي يكفي صفحة A4 واحدة ('+h+')');
  await p.screenshot({path:OUT+'report-screen.png',fullPage:true});
  console.log('8. الإرسال للموجه');
  ok(await p.isVisible('#anSendBtn'),'زر الإرسال ظاهر للمدرسة');
  await p.click('#anSendBtn'); await p.waitForTimeout(700);
  ok((await p.locator('#anRecip option').count())===1,'الموجه الطلابي فقط في القائمة');
  await p.evaluate(()=>{ closeOmrModal(); window.__mockWrites.length=0; });
  await p.check('#anClasses input.anc[value="م1ب"]'); await p.waitForTimeout(200);
  await p.evaluate(()=>anSend()); await p.waitForTimeout(700);
  ok(/٢<\/b> ملف PDF/.test(await p.innerHTML('#omrModalOv')) || /٢/.test(await p.textContent('#omrModalOv')),'نافذة الإرسال تذكر ملفين');
  await p.evaluate(()=>{ anDoSend(); }); await p.waitForTimeout(6000);
  const w=await p.evaluate(()=>window.__mockWrites.filter(x=>/^notes\//.test(x.path)).map(x=>x.data));
  ok(w.length===2 && w.every(x=>x.scope==='report' && x.recipients[0]==='c1' && x.schoolId==='S2'),'ملاحظتان (لكل فصل) للموجه فقط: '+w.length);
  ok(w.every(x=>typeof x.pdfB64==='string' && x.pdfB64.startsWith('JVBERi0')),'كل ملاحظة تحمل ملف PDF صالح الترويسة');
  ok(w.every(x=>x.pdfB64.length<420000),'حجم كل ملف ضمن الحد: '+w.map(x=>Math.round(x.pdfB64.length/1024)+'KB').join(' / '));
  ok(w.every(x=>!/ممتاز/.test(x.text)) && /م1أ|أول متوسط \(أ\)/.test(w[0].text+w[1].text),'النص عنوان فقط بلا إحصاءات: '+w[0].text);
  ok(w.every(x=>/\.pdf$/.test(x.pdfName)),'اسم الملف: '+w[0].pdfName);
  w.forEach((x,i)=>fs.writeFileSync(OUT+'sent-'+i+'.pdf',Buffer.from(x.pdfB64,'base64')));
  await p.uncheck('#anClasses input.anc[value="م1ب"]'); await p.waitForTimeout(150);
  console.log('9. الفردي لا يرى الإرسال');
  const SO={userId:'solo1',username:'فردي',role:'soloTeacher',schoolId:null,period:'first',ctxKey:'solo'};
  const ps=await mk(SO,{'users/solo1':{authUid:'U_solo1',active:true,isSolo:true,username:'فردي',solo:{active:true,subscriptionEnds:Date.now()+1e10}}});
  await ps.evaluate(()=>showTab('cloud')); await ps.click('#cloudSubAn').catch(()=>{}); await ps.waitForTimeout(300);
  ok(!(await ps.isVisible('#anSendBtn')),'زر الإرسال مخفي للحساب الفردي');
  console.log('10. العودة لسجل النتائج');
  await p.click('#cloudSubLog'); ok(await p.isVisible('#cloudLogWrap') && !(await p.isVisible('#resAnCard')),'رجوع');
  // جوال
  const pm=await mk(S,DB); await pm.setViewportSize({width:390,height:844}); await pm.evaluate(()=>showTab('cloud')); await pm.click('#cloudSubAn'); await pm.check('#anClasses input.anc[value="م1أ"]'); await pm.waitForTimeout(300);
  const ov=await pm.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2); ok(!ov,'لا تمرير أفقي للصفحة على الجوال'); if(ov) console.log(await pm.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>window.innerWidth+2).slice(0,6).map(e=>e.tagName+'.'+e.className+'#'+e.id+':'+Math.round(e.getBoundingClientRect().right))));
  await pm.screenshot({path:OUT+'report-phone.png',fullPage:true});
  await b.close(); console.log(FAIL?('\nفشل '+FAIL):'\nكل الفحوص نجحت','· أخطاء صفحات:',ERRS); process.exit(FAIL||ERRS?1:0);
})();
