const { chromium } = require('playwright'); const fs=require('fs');
const MOCK = fs.readFileSync(__dirname+'/mock-firebase.js','utf8');
const DB = JSON.parse(fs.readFileSync(__dirname+'/db-after.json','utf8'));
(async()=>{
  const b=await chromium.launch(); const ctx=await b.newContext();
  await ctx.route(/jsdelivr|cdnjs|googleapis|gstatic/, r=>r.fulfill({ status:200, body:'' }));
  await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat/, r=>r.fulfill({ status:200, contentType:'application/javascript', body: MOCK }));
  await ctx.addInitScript(([s,db])=>{ window.__mockUid='U_SA1'; localStorage.setItem('cls_session', JSON.stringify(s)); localStorage.setItem('__mockdb', JSON.stringify(db)); window.alert=(m)=>{ (window.__alerts=window.__alerts||[]).push(m); }; window.confirm=()=>true; }, [{ userId:'sa1', username:'ياسر', role:'schoolAdmin', schoolId:'S2', period:'first' }, DB]);
  const p=await ctx.newPage(); p.on('pageerror', e=>console.log('ERR', e.message));
  await p.goto('http://127.0.0.1:8765/omr.html'); await p.waitForTimeout(2500);
  console.log('u1 before', JSON.stringify(await p.evaluate(()=>__mockDB()['users/u1'].schools.S2.subjectAssignmentsByPeriod.first.map(a=>a.classCode))));
  await p.evaluate(()=>{ let n=0; window.prompt=(q,d)=>{ n++; return n===1 ? d : 'م9ز'; }; });
  await p.evaluate(()=>ciEditClass('م1ب')); await p.waitForTimeout(800);
  console.log('alerts', JSON.stringify(await p.evaluate(()=>window.__alerts||[])));
  console.log('class', await p.evaluate(()=>JSON.stringify(state.fullClasses.map(c=>c.code))));
  const w = await p.evaluate(()=>__mockWrites.filter(x=>x.path==='users/u1').map(x=>Object.keys(x.data)));
  console.log('writes u1', JSON.stringify(w));
  console.log('u1 after', JSON.stringify(await p.evaluate(()=>__mockDB()['users/u1'].schools.S2.subjectAssignmentsByPeriod.first.map(a=>a.classCode))));
  await b.close();
})();
