const { chromium, devices } = require('playwright'); const fs=require('fs');
const MOCK = fs.readFileSync(__dirname+'/mock-firebase.js','utf8');
const DB = { 'users/sa1':{username:'ي',role:'schoolAdmin',authUid:'U_sa1',active:true,adminSchools:['S2']}, 'schoolData/S2':{name:'مدرسة'} };
let bad=0; const ck=(n,c)=>{console.log((c?'✓ ':'✗ ')+n); if(!c)bad++;};
(async()=>{ const b=await chromium.launch(); const ctx=await b.newContext({...devices['Pixel 5']});
 await ctx.route(/cdnjs|googleapis|jsdelivr/, r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
 await ctx.route(/gstatic\.com\/firebasejs\/.*firebase-app-compat/, r=>r.fulfill({status:200,contentType:'application/javascript',body:MOCK}));
 await ctx.route(/gstatic\.com\/firebasejs\/.*(firestore|auth)-compat/, r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
 await ctx.addInitScript(([s,db])=>{window.__mockUid='U_sa1';localStorage.setItem('cls_session',JSON.stringify(s));localStorage.setItem('__mockdb',JSON.stringify(db));},[{userId:'sa1',username:'ي',role:'schoolAdmin',schoolId:'S2',period:'first',ctxKey:'school:S2'},DB]);
 const p=await ctx.newPage(); p.on('pageerror',e=>{console.log('ERR',e.message);bad++});
 await p.goto('http://127.0.0.1:8765/holidays.html'); await p.waitForTimeout(1500);
 const mode=()=>p.evaluate(()=>HS.mode);
 ck('الافتراضي يوم واحد', await mode()==='one');
 await p.fill('#hFrom','2026-12-06'); await p.fill('#hLabel','وصف'); await p.tap('#qOn');
 ck('التفعيل يعمل', await p.$eval('#qOn',e=>e.checked));
 ck('التاريخ والوصف باقيان', await p.$eval('#hFrom',e=>e.value)==='2026-12-06' && await p.$eval('#hLabel',e=>e.value)==='وصف');
 ck('الوضع لم يتغير', await mode()==='one');
 await p.tap('[data-hmode=range]'); ck('من–إلى يعمل', await mode()==='range' && !!(await p.$('#hTo')));
 await p.tap('[data-hmode=one]'); ck('رجوع ليوم واحد', await mode()==='one');
 await p.fill('#hFrom','2026-12-06'); await p.fill('#hLabel','اختبار'); await p.tap('#hAdd'); await p.waitForTimeout(500);
 ck('أُضيفت إجازة', (await p.$$('[data-del]')).length===1);
 await p.tap('[data-mode=dark]').catch(()=>{});
 await p.fill('#qFrom','20:00'); await p.tap('#qOn'); await p.tap('#qSave'); await p.waitForTimeout(400);
 ck('حفظ الهدوء', await p.evaluate(()=>HS.cal.quiet.on===true||HS.cal.quiet.on===false));
 await b.close(); console.log(bad?'FAIL':'ALL OK'); process.exit(bad?1:0);})();
